# Conda environment file
# Create a new Conda environment for development with:
# `conda env create -f environment.yml`
# Activate environment:
# `conda activate dokknet_example`
name: dokknet_example
dependencies:
  - python=3.8
  - ipython
  - pip
  - pip:
      - -rrequirements/dev-requirements.txt
